name: MC-MapControl
version: '1.0-SNAPSHOT'
main: com.draconincdomain.mapcontrol.MapControl
api-version: '1.21'
commands:
  party:
    description: "Will spawn a custom entity from the custom mob enum"
    usage: "/party"
    permission: party.admin
  aparty: